// <auto-generated>
//     Generated by protobus-codegen from chat.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Chat;

/// <summary>
/// protobus bindings for <c>Chat.Assistant</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class AssistantProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "Chat.Assistant";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Chat.ChatReflection.Descriptor;

    /// <summary>
    /// Implements <c>Chat.Assistant</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterStream<global::Chat.GenerateRequest, global::Chat.Token>("generate", global::Chat.GenerateRequest.Parser, Generate);
            RegisterUnary<global::Chat.StatsRequest, global::Chat.StatsResponse>("stats", global::Chat.StatsRequest.Parser, Stats);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc generate(Chat.GenerateRequest) returns (stream Chat.Token)</c></summary>
        public virtual global::System.Collections.Generic.IAsyncEnumerable<global::Chat.Token> Generate(global::Chat.GenerateRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method generate");

        /// <summary><c>rpc stats(Chat.StatsRequest) returns (Chat.StatsResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Chat.StatsResponse> Stats(global::Chat.StatsRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method stats");
    }

    /// <summary>
    /// Calls <c>Chat.Assistant</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc generate(Chat.GenerateRequest) returns (stream Chat.Token)</c></summary>
        public global::System.Collections.Generic.IAsyncEnumerable<global::Chat.Token> Generate(global::Chat.GenerateRequest request, global::Protobus.StreamOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallStream("generate", request, global::Chat.Token.Parser, options, cancellationToken);

        /// <summary><c>rpc stats(Chat.StatsRequest) returns (Chat.StatsResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Chat.StatsResponse> StatsAsync(global::Chat.StatsRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("stats", request, global::Chat.StatsResponse.Parser, options, cancellationToken);
    }
}
