// <auto-generated>
//     Generated by protobus-codegen from player.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Combat;

/// <summary>
/// protobus bindings for <c>Combat.Player</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class PlayerProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "Combat.Player";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Combat.PlayerReflection.Descriptor;

    /// <summary>
    /// Implements <c>Combat.Player</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Combat.ShootRequest, global::Combat.ShootResponse>("shoot", global::Combat.ShootRequest.Parser, Shoot);
            RegisterUnary<global::Combat.InitiateGameRequest, global::Combat.InitiateGameResponse>("initiateGame", global::Combat.InitiateGameRequest.Parser, InitiateGame);
            RegisterUnary<global::Combat.GetStatusRequest, global::Combat.GetStatusResponse>("getStatus", global::Combat.GetStatusRequest.Parser, GetStatus);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc shoot(Combat.ShootRequest) returns (Combat.ShootResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Combat.ShootResponse> Shoot(global::Combat.ShootRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method shoot");

        /// <summary><c>rpc initiateGame(Combat.InitiateGameRequest) returns (Combat.InitiateGameResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Combat.InitiateGameResponse> InitiateGame(global::Combat.InitiateGameRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method initiateGame");

        /// <summary><c>rpc getStatus(Combat.GetStatusRequest) returns (Combat.GetStatusResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Combat.GetStatusResponse> GetStatus(global::Combat.GetStatusRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method getStatus");
    }

    /// <summary>
    /// Calls <c>Combat.Player</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc shoot(Combat.ShootRequest) returns (Combat.ShootResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Combat.ShootResponse> ShootAsync(global::Combat.ShootRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("shoot", request, global::Combat.ShootResponse.Parser, options, cancellationToken);

        /// <summary><c>rpc initiateGame(Combat.InitiateGameRequest) returns (Combat.InitiateGameResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Combat.InitiateGameResponse> InitiateGameAsync(global::Combat.InitiateGameRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("initiateGame", request, global::Combat.InitiateGameResponse.Parser, options, cancellationToken);

        /// <summary><c>rpc getStatus(Combat.GetStatusRequest) returns (Combat.GetStatusResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Combat.GetStatusResponse> GetStatusAsync(global::Combat.GetStatusRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("getStatus", request, global::Combat.GetStatusResponse.Parser, options, cancellationToken);
    }
}
