// <auto-generated>
//     Generated by protobus-codegen from Calculator.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Calculator;

/// <summary>
/// protobus bindings for <c>Calculator.Service</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class ServiceProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "Calculator.Service";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Calculator.CalculatorReflection.Descriptor;

    /// <summary>
    /// Implements <c>Calculator.Service</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Calculator.AddRequest, global::Calculator.AddResponse>("add", global::Calculator.AddRequest.Parser, Add);
            RegisterUnary<global::Calculator.DivideRequest, global::Calculator.DivideResponse>("divide", global::Calculator.DivideRequest.Parser, Divide);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc add(Calculator.AddRequest) returns (Calculator.AddResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Calculator.AddResponse> Add(global::Calculator.AddRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method add");

        /// <summary><c>rpc divide(Calculator.DivideRequest) returns (Calculator.DivideResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Calculator.DivideResponse> Divide(global::Calculator.DivideRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method divide");
    }

    /// <summary>
    /// Calls <c>Calculator.Service</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc add(Calculator.AddRequest) returns (Calculator.AddResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Calculator.AddResponse> AddAsync(global::Calculator.AddRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("add", request, global::Calculator.AddResponse.Parser, options, cancellationToken);

        /// <summary><c>rpc divide(Calculator.DivideRequest) returns (Calculator.DivideResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Calculator.DivideResponse> DivideAsync(global::Calculator.DivideRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("divide", request, global::Calculator.DivideResponse.Parser, options, cancellationToken);
    }
}
