// <auto-generated>
//     Generated by protobus-codegen from interop.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Interop;

/// <summary>
/// protobus bindings for <c>interop.Flaky</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class FlakyProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "interop.Flaky";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Interop.InteropReflection.Descriptor;

    /// <summary>
    /// Implements <c>interop.Flaky</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Interop.FailRequest, global::Interop.Nothing>("fail", global::Interop.FailRequest.Parser, Fail);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc fail(interop.FailRequest) returns (interop.Nothing)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Interop.Nothing> Fail(global::Interop.FailRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method fail");
    }

    /// <summary>
    /// Calls <c>interop.Flaky</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc fail(interop.FailRequest) returns (interop.Nothing)</c></summary>
        public global::System.Threading.Tasks.Task<global::Interop.Nothing> FailAsync(global::Interop.FailRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("fail", request, global::Interop.Nothing.Parser, options, cancellationToken);
    }
}
