<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="../../src/Protobus.Tools/build/Protobus.Tools.props" />

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
    <ProtobusCodegenDll>$(MSBuildThisFileDirectory)../../src/Protobus.Codegen/bin/$(Configuration)/net8.0/protobus-csharp.dll</ProtobusCodegenDll>
  </PropertyGroup>

  <ItemGroup>
    <ProtobusSchemas Include="../proto" />
    <Content Include="../../tests/Protobus.Tests/xunit.runner.json" Link="xunit.runner.json" CopyToOutputDirectory="PreserveNewest" />
    <AssemblyMetadata Include="CrossLangDir" Value="$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)..'))" />
    <AssemblyMetadata Include="CSharpPeer" Value="$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)../CSharpPeer/bin/$(Configuration)/net8.0/CSharpPeer.dll'))" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="Grpc.Tools" PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/Protobus/Protobus.csproj" />
    <ProjectReference Include="../../src/Protobus.Codegen/Protobus.Codegen.csproj" ReferenceOutputAssembly="false" />
    <ProjectReference Include="../CSharpPeer/CSharpPeer.csproj" ReferenceOutputAssembly="false" />
  </ItemGroup>

  <Import Project="../../src/Protobus.Tools/build/Protobus.Tools.targets" />
</Project>
