// <auto-generated>
//     Generated by protobus-codegen from pbtest.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Pbtest;

/// <summary>
/// protobus bindings for <c>pbtest.Calc</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class CalcProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "pbtest.Calc";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Pbtest.PbtestReflection.Descriptor;

    /// <summary>
    /// Implements <c>pbtest.Calc</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Pbtest.AddRequest, global::Pbtest.AddResponse>("add", global::Pbtest.AddRequest.Parser, Add);
            RegisterUnary<global::Pbtest.DivideRequest, global::Pbtest.DivideResponse>("divide", global::Pbtest.DivideRequest.Parser, Divide);
            RegisterUnary<global::Pbtest.FailRequest, global::Pbtest.Nothing>("fail", global::Pbtest.FailRequest.Parser, Fail);
            RegisterUnary<global::Pbtest.SlowRequest, global::Pbtest.Nothing>("slow", global::Pbtest.SlowRequest.Parser, Slow);
            RegisterStream<global::Pbtest.TickRequest, global::Pbtest.Tick>("ticks", global::Pbtest.TickRequest.Parser, Ticks);
            RegisterUnary<global::Pbtest.Nothing, global::Pbtest.Who>("whoami", global::Pbtest.Nothing.Parser, Whoami);
            RegisterUnary<global::Pbtest.Nothing, global::Pbtest.Nothing>("unimplemented", global::Pbtest.Nothing.Parser, Unimplemented);
            RegisterUnary<global::Pbtest.Wallet, global::Pbtest.Wallet>("echo", global::Pbtest.Wallet.Parser, Echo);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc add(pbtest.AddRequest) returns (pbtest.AddResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.AddResponse> Add(global::Pbtest.AddRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method add");

        /// <summary><c>rpc divide(pbtest.DivideRequest) returns (pbtest.DivideResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.DivideResponse> Divide(global::Pbtest.DivideRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method divide");

        /// <summary><c>rpc fail(pbtest.FailRequest) returns (pbtest.Nothing)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.Nothing> Fail(global::Pbtest.FailRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method fail");

        /// <summary><c>rpc slow(pbtest.SlowRequest) returns (pbtest.Nothing)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.Nothing> Slow(global::Pbtest.SlowRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method slow");

        /// <summary><c>rpc ticks(pbtest.TickRequest) returns (stream pbtest.Tick)</c></summary>
        public virtual global::System.Collections.Generic.IAsyncEnumerable<global::Pbtest.Tick> Ticks(global::Pbtest.TickRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method ticks");

        /// <summary><c>rpc whoami(pbtest.Nothing) returns (pbtest.Who)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.Who> Whoami(global::Pbtest.Nothing request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method whoami");

        /// <summary><c>rpc unimplemented(pbtest.Nothing) returns (pbtest.Nothing)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.Nothing> Unimplemented(global::Pbtest.Nothing request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method unimplemented");

        /// <summary><c>rpc echo(pbtest.Wallet) returns (pbtest.Wallet)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Pbtest.Wallet> Echo(global::Pbtest.Wallet request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method echo");
    }

    /// <summary>
    /// Calls <c>pbtest.Calc</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc add(pbtest.AddRequest) returns (pbtest.AddResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.AddResponse> AddAsync(global::Pbtest.AddRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("add", request, global::Pbtest.AddResponse.Parser, options, cancellationToken);

        /// <summary><c>rpc divide(pbtest.DivideRequest) returns (pbtest.DivideResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.DivideResponse> DivideAsync(global::Pbtest.DivideRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("divide", request, global::Pbtest.DivideResponse.Parser, options, cancellationToken);

        /// <summary><c>rpc fail(pbtest.FailRequest) returns (pbtest.Nothing)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.Nothing> FailAsync(global::Pbtest.FailRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("fail", request, global::Pbtest.Nothing.Parser, options, cancellationToken);

        /// <summary><c>rpc slow(pbtest.SlowRequest) returns (pbtest.Nothing)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.Nothing> SlowAsync(global::Pbtest.SlowRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("slow", request, global::Pbtest.Nothing.Parser, options, cancellationToken);

        /// <summary><c>rpc ticks(pbtest.TickRequest) returns (stream pbtest.Tick)</c></summary>
        public global::System.Collections.Generic.IAsyncEnumerable<global::Pbtest.Tick> Ticks(global::Pbtest.TickRequest request, global::Protobus.StreamOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallStream("ticks", request, global::Pbtest.Tick.Parser, options, cancellationToken);

        /// <summary><c>rpc whoami(pbtest.Nothing) returns (pbtest.Who)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.Who> WhoamiAsync(global::Pbtest.Nothing request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("whoami", request, global::Pbtest.Who.Parser, options, cancellationToken);

        /// <summary><c>rpc unimplemented(pbtest.Nothing) returns (pbtest.Nothing)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.Nothing> UnimplementedAsync(global::Pbtest.Nothing request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("unimplemented", request, global::Pbtest.Nothing.Parser, options, cancellationToken);

        /// <summary><c>rpc echo(pbtest.Wallet) returns (pbtest.Wallet)</c></summary>
        public global::System.Threading.Tasks.Task<global::Pbtest.Wallet> EchoAsync(global::Pbtest.Wallet request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("echo", request, global::Pbtest.Wallet.Parser, options, cancellationToken);
    }
}
