// <auto-generated>
//     Generated by protobus-codegen from naming.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Naming;

/// <summary>
/// protobus bindings for <c>naming.Naming</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class NamingProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "naming.Naming";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Naming.NamingReflection.Descriptor;

    /// <summary>
    /// Implements <c>naming.Naming</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Naming.Req, global::Naming.Res>("fetch", global::Naming.Req.Parser, Fetch);
            RegisterUnary<global::Naming.Req, global::Naming.Res>("fetchAsync", global::Naming.Req.Parser, FetchAsync);
            RegisterUnary<global::Naming.Req, global::Naming.Res>("fetchAsyncAsync", global::Naming.Req.Parser, FetchAsyncAsync);
            RegisterStream<global::Naming.Req, global::Naming.Res>("watch", global::Naming.Req.Parser, Watch);
            RegisterUnary<global::Naming.Req, global::Naming.Res>("watchAsync", global::Naming.Req.Parser, WatchAsync);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc fetch(naming.Req) returns (naming.Res)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Naming.Res> Fetch(global::Naming.Req request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method fetch");

        /// <summary><c>rpc fetchAsync(naming.Req) returns (naming.Res)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Naming.Res> FetchAsync(global::Naming.Req request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method fetchAsync");

        /// <summary><c>rpc fetchAsyncAsync(naming.Req) returns (naming.Res)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Naming.Res> FetchAsyncAsync(global::Naming.Req request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method fetchAsyncAsync");

        /// <summary><c>rpc watch(naming.Req) returns (stream naming.Res)</c></summary>
        public virtual global::System.Collections.Generic.IAsyncEnumerable<global::Naming.Res> Watch(global::Naming.Req request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method watch");

        /// <summary><c>rpc watchAsync(naming.Req) returns (naming.Res)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Naming.Res> WatchAsync(global::Naming.Req request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method watchAsync");
    }

    /// <summary>
    /// Calls <c>naming.Naming</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc fetch(naming.Req) returns (naming.Res)</c></summary>
        public global::System.Threading.Tasks.Task<global::Naming.Res> FetchAsync_(global::Naming.Req request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("fetch", request, global::Naming.Res.Parser, options, cancellationToken);

        /// <summary><c>rpc fetchAsync(naming.Req) returns (naming.Res)</c></summary>
        public global::System.Threading.Tasks.Task<global::Naming.Res> FetchAsyncAsync_(global::Naming.Req request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("fetchAsync", request, global::Naming.Res.Parser, options, cancellationToken);

        /// <summary><c>rpc fetchAsyncAsync(naming.Req) returns (naming.Res)</c></summary>
        public global::System.Threading.Tasks.Task<global::Naming.Res> FetchAsyncAsyncAsync(global::Naming.Req request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("fetchAsyncAsync", request, global::Naming.Res.Parser, options, cancellationToken);

        /// <summary><c>rpc watch(naming.Req) returns (stream naming.Res)</c></summary>
        public global::System.Collections.Generic.IAsyncEnumerable<global::Naming.Res> Watch(global::Naming.Req request, global::Protobus.StreamOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallStream("watch", request, global::Naming.Res.Parser, options, cancellationToken);

        /// <summary><c>rpc watchAsync(naming.Req) returns (naming.Res)</c></summary>
        public global::System.Threading.Tasks.Task<global::Naming.Res> WatchAsyncAsync(global::Naming.Req request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("watchAsync", request, global::Naming.Res.Parser, options, cancellationToken);
    }
}
