// <auto-generated>
//     Generated by protobus-codegen from deep/nested.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Deep.Pkg;

/// <summary>
/// protobus bindings for <c>deep.pkg.Store</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class StoreProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "deep.pkg.Store";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Deep.Pkg.NestedReflection.Descriptor;

    /// <summary>
    /// Implements <c>deep.pkg.Store</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Deep.Pkg.Key, global::Deep.Pkg.Item>("delete", global::Deep.Pkg.Key.Parser, Delete);
            RegisterUnary<global::Deep.Pkg.Key, global::Deep.Pkg.Item>("init", global::Deep.Pkg.Key.Parser, Init_);
            RegisterStream<global::Deep.Pkg.Key, global::Deep.Pkg.Item>("list", global::Deep.Pkg.Key.Parser, List);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc delete(deep.pkg.Key) returns (deep.pkg.Item)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Deep.Pkg.Item> Delete(global::Deep.Pkg.Key request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method delete");

        /// <summary><c>rpc init(deep.pkg.Key) returns (deep.pkg.Item)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Deep.Pkg.Item> Init_(global::Deep.Pkg.Key request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method init");

        /// <summary><c>rpc list(deep.pkg.Key) returns (stream deep.pkg.Item)</c></summary>
        public virtual global::System.Collections.Generic.IAsyncEnumerable<global::Deep.Pkg.Item> List(global::Deep.Pkg.Key request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method list");
    }

    /// <summary>
    /// Calls <c>deep.pkg.Store</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc delete(deep.pkg.Key) returns (deep.pkg.Item)</c></summary>
        public global::System.Threading.Tasks.Task<global::Deep.Pkg.Item> DeleteAsync(global::Deep.Pkg.Key request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("delete", request, global::Deep.Pkg.Item.Parser, options, cancellationToken);

        /// <summary><c>rpc init(deep.pkg.Key) returns (deep.pkg.Item)</c></summary>
        public global::System.Threading.Tasks.Task<global::Deep.Pkg.Item> InitAsync_(global::Deep.Pkg.Key request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("init", request, global::Deep.Pkg.Item.Parser, options, cancellationToken);

        /// <summary><c>rpc list(deep.pkg.Key) returns (stream deep.pkg.Item)</c></summary>
        public global::System.Collections.Generic.IAsyncEnumerable<global::Deep.Pkg.Item> List(global::Deep.Pkg.Key request, global::Protobus.StreamOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallStream("list", request, global::Deep.Pkg.Item.Parser, options, cancellationToken);
    }
}
