// <auto-generated>
//     Generated by protobus-codegen from interop.proto. Do not edit.
// </auto-generated>
#pragma warning disable 1591, 0612, 3021, 8981
#nullable enable
namespace Interop;

/// <summary>
/// protobus bindings for <c>interop.Counter</c>: implement it by extending
/// <see cref="Base"/>; call it with <see cref="Proxy"/>.
/// </summary>
[global::System.CodeDom.Compiler.GeneratedCode("protobus-codegen", null)]
public static partial class CounterProtobus
{
    /// <summary>The service's name on the bus, and its contract.</summary>
    public const string ServiceFullName = "interop.Counter";

    /// <summary>The schema declaring the service.</summary>
    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => global::Interop.InteropReflection.Descriptor;

    /// <summary>
    /// Implements <c>interop.Counter</c>: override its rpcs. An rpc left unimplemented
    /// answers PROTOCOL_ERROR. Throw a <see cref="global::Protobus.HandledError"/> to answer the caller
    /// with an error; anything else thrown is retried.
    /// </summary>
    public abstract partial class Base : global::Protobus.RunnableService
    {
        protected Base(global::Protobus.Context context, global::Protobus.MessageServiceOptions? options = null) : base(context, options)
        {
            RegisterUnary<global::Interop.AddRequest, global::Interop.AddResponse>("add", global::Interop.AddRequest.Parser, Add);
            RegisterStream<global::Interop.TickRequest, global::Interop.Tick>("tick", global::Interop.TickRequest.Parser, Tick);
            RegisterUnary<global::Interop.Nothing, global::Interop.Produced>("produced", global::Interop.Nothing.Parser, Produced);
            RegisterUnary<global::Interop.Nothing, global::Interop.Who>("whoami", global::Interop.Nothing.Parser, Whoami);
            RegisterUnary<global::Interop.Nothing, global::Interop.Nothing>("unimplemented", global::Interop.Nothing.Parser, Unimplemented);
        }

        /// <inheritdoc/>
        public override string ServiceName => ServiceFullName;

        /// <inheritdoc/>
        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;

        /// <summary><c>rpc add(interop.AddRequest) returns (interop.AddResponse)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Interop.AddResponse> Add(global::Interop.AddRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method add");

        /// <summary><c>rpc tick(interop.TickRequest) returns (stream interop.Tick)</c></summary>
        public virtual global::System.Collections.Generic.IAsyncEnumerable<global::Interop.Tick> Tick(global::Interop.TickRequest request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method tick");

        /// <summary><c>rpc produced(interop.Nothing) returns (interop.Produced)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Interop.Produced> Produced(global::Interop.Nothing request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method produced");

        /// <summary><c>rpc whoami(interop.Nothing) returns (interop.Who)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Interop.Who> Whoami(global::Interop.Nothing request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method whoami");

        /// <summary><c>rpc unimplemented(interop.Nothing) returns (interop.Nothing)</c></summary>
        public virtual global::System.Threading.Tasks.Task<global::Interop.Nothing> Unimplemented(global::Interop.Nothing request, global::Protobus.CallContext context) =>
            throw new global::Protobus.InvalidMethodError("invalid service method unimplemented");
    }

    /// <summary>
    /// Calls <c>interop.Counter</c>. Construct it with an instance name to address a
    /// service registered under one; <see cref="global::Protobus.ServiceProxy.Init"/> before calling.
    /// </summary>
    public partial class Proxy : global::Protobus.ServiceProxy
    {
        public Proxy(global::Protobus.Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>
            context.Factory.Register(Descriptor);

        /// <summary><c>rpc add(interop.AddRequest) returns (interop.AddResponse)</c></summary>
        public global::System.Threading.Tasks.Task<global::Interop.AddResponse> AddAsync(global::Interop.AddRequest request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("add", request, global::Interop.AddResponse.Parser, options, cancellationToken);

        /// <summary><c>rpc tick(interop.TickRequest) returns (stream interop.Tick)</c></summary>
        public global::System.Collections.Generic.IAsyncEnumerable<global::Interop.Tick> Tick(global::Interop.TickRequest request, global::Protobus.StreamOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallStream("tick", request, global::Interop.Tick.Parser, options, cancellationToken);

        /// <summary><c>rpc produced(interop.Nothing) returns (interop.Produced)</c></summary>
        public global::System.Threading.Tasks.Task<global::Interop.Produced> ProducedAsync(global::Interop.Nothing request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("produced", request, global::Interop.Produced.Parser, options, cancellationToken);

        /// <summary><c>rpc whoami(interop.Nothing) returns (interop.Who)</c></summary>
        public global::System.Threading.Tasks.Task<global::Interop.Who> WhoamiAsync(global::Interop.Nothing request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("whoami", request, global::Interop.Who.Parser, options, cancellationToken);

        /// <summary><c>rpc unimplemented(interop.Nothing) returns (interop.Nothing)</c></summary>
        public global::System.Threading.Tasks.Task<global::Interop.Nothing> UnimplementedAsync(global::Interop.Nothing request, global::Protobus.CallOptions? options = null,
            global::System.Threading.CancellationToken cancellationToken = default) =>
            CallAsync("unimplemented", request, global::Interop.Nothing.Parser, options, cancellationToken);
    }
}
