using System.Collections.Generic;
using System.Text;
using Google.Protobuf.Reflection;

namespace Protobus.Codegen;

/// <summary>
/// Writes the protobus classes for one schema: per service, a <c>&lt;Service&gt;Protobus</c>
/// holding the service's name, an abstract <c>Base</c> to implement and a typed <c>Proxy</c> to
/// call it with.
/// </summary>
internal static class Generator
{
    internal sealed record Output(string Path, string Content);

    private const string Rt = "global::Protobus.";
    private const string Tasks = "global::System.Threading.Tasks.";
    private const string Async = "global::System.Collections.Generic.IAsyncEnumerable";
    private const string Token = "global::System.Threading.CancellationToken";

    internal static List<Output> Generate(FileDescriptor file)
    {
        var o = new List<Output>();
        foreach (var s in file.Services) o.Add(new Output(s.Name + "Protobus.cs", Service(file, s, s.Name + "Protobus")));
        return o;
    }

    /// <summary>
    /// The C# names of a service's methods, allocated together so none collide: an rpc's own name,
    /// PascalCased, for the base's handler and a streaming proxy method, and for a unary rpc its
    /// <c>Async</c> proxy method. A name already taken, by a base-class member, another rpc or
    /// another variant, gets underscores until it is free, so <c>fetch</c> and <c>fetch_async</c>
    /// side by side give <c>FetchAsync_</c> for the first one's proxy method.
    /// </summary>
    internal sealed record MethodNames(Dictionary<string, string> Plain, Dictionary<string, string> Async)
    {
        internal static MethodNames Allocate(ServiceDescriptor s)
        {
            var taken = new HashSet<string>(Names.ReservedMembers);
            var plain = new Dictionary<string, string>();
            var async = new Dictionary<string, string>();
            // The rpcs' own names first: they are what callers look for.
            foreach (var m in s.Methods)
            {
                if (m.IsClientStreaming) continue;
                plain[m.Name] = Claim(taken, Identifier(m.Name));
            }
            foreach (var m in s.Methods)
            {
                if (m.IsClientStreaming || m.IsServerStreaming) continue;
                async[m.Name] = Claim(taken, plain[m.Name].TrimEnd('_') + "Async");
            }
            return new MethodNames(plain, async);
        }

        /// <summary>A name C# accepts as a method: PascalCased, and never empty or led by a digit.</summary>
        private static string Identifier(string rpc)
        {
            var p = Names.Pascal(rpc);
            return p.Length == 0 || char.IsDigit(p[0]) ? "Rpc" + p : p;
        }

        private static string Claim(HashSet<string> taken, string name)
        {
            var n = name;
            while (taken.Contains(n)) n += "_";
            taken.Add(n);
            return n;
        }
    }

    private static string Signature(MethodDescriptor m) =>
        $"rpc {m.Name}({(m.IsClientStreaming ? "stream " : "")}{m.InputType.FullName}) returns "
        + $"({(m.IsServerStreaming ? "stream " : "")}{m.OutputType.FullName})";

    private static string Service(FileDescriptor file, ServiceDescriptor s, string cls)
    {
        var b = new StringBuilder();
        var ns = Names.Namespace(file);
        b.Append("// <auto-generated>\n//     Generated by protobus-codegen from ").Append(file.Name).Append(". Do not edit.\n// </auto-generated>\n");
        b.Append("#pragma warning disable 1591, 0612, 3021, 8981\n#nullable enable\n");
        if (ns.Length > 0) b.Append("namespace ").Append(ns).Append(";\n");
        b.Append('\n');
        b.Append("/// <summary>\n/// protobus bindings for <c>").Append(s.FullName).Append("</c>: implement it by extending\n");
        b.Append("/// <see cref=\"Base\"/>; call it with <see cref=\"Proxy\"/>.\n/// </summary>\n");
        b.Append("[global::System.CodeDom.Compiler.GeneratedCode(\"protobus-codegen\", null)]\n");
        b.Append("public static partial class ").Append(cls).Append("\n{\n");
        b.Append("    /// <summary>The service's name on the bus, and its contract.</summary>\n");
        b.Append("    public const string ServiceFullName = \"").Append(s.FullName).Append("\";\n\n");
        b.Append("    /// <summary>The schema declaring the service.</summary>\n");
        b.Append("    public static global::Google.Protobuf.Reflection.FileDescriptor Descriptor => ")
            .Append(Names.ReflectionClass(file)).Append(".Descriptor;\n\n");
        var names = MethodNames.Allocate(s);
        Base(b, s, names);
        b.Append('\n');
        Proxy(b, s, names);
        b.Append("}\n");
        return b.ToString();
    }

    private static void Base(StringBuilder b, ServiceDescriptor s, MethodNames names)
    {
        b.Append("    /// <summary>\n");
        b.Append("    /// Implements <c>").Append(s.FullName).Append("</c>: override its rpcs. An rpc left unimplemented\n");
        b.Append("    /// answers PROTOCOL_ERROR. Throw a <see cref=\"").Append(Rt).Append("HandledError\"/> to answer the caller\n");
        b.Append("    /// with an error; anything else thrown is retried.\n    /// </summary>\n");
        b.Append("    public abstract partial class Base : ").Append(Rt).Append("RunnableService\n    {\n");
        b.Append("        protected Base(").Append(Rt).Append("Context context, ").Append(Rt)
            .Append("MessageServiceOptions? options = null) : base(context, options)\n        {\n");
        foreach (var m in s.Methods)
        {
            if (m.IsClientStreaming) continue;
            var req = Names.MessageClass(m.InputType);
            var res = Names.MessageClass(m.OutputType);
            b.Append("            Register").Append(m.IsServerStreaming ? "Stream" : "Unary").Append('<').Append(req).Append(", ")
                .Append(res).Append(">(\"").Append(m.Name).Append("\", ").Append(req).Append(".Parser, ")
                .Append(names.Plain[m.Name]).Append(");\n");
        }
        b.Append("        }\n\n");
        b.Append("        /// <inheritdoc/>\n        public override string ServiceName => ServiceFullName;\n\n");
        b.Append("        /// <inheritdoc/>\n        protected override global::Google.Protobuf.Reflection.FileDescriptor? Schema => Descriptor;\n");
        foreach (var m in s.Methods)
        {
            b.Append("\n        /// <summary><c>").Append(Signature(m)).Append("</c></summary>\n");
            if (m.IsClientStreaming)
            {
                b.Append("        // Client streaming is not part of the protobus protocol; this rpc is not served.\n");
                continue;
            }
            var req = Names.MessageClass(m.InputType);
            var res = Names.MessageClass(m.OutputType);
            var id = names.Plain[m.Name];
            b.Append("        public virtual ")
                .Append(m.IsServerStreaming ? $"{Async}<{res}>" : $"{Tasks}Task<{res}>")
                .Append(' ').Append(id).Append('(').Append(req).Append(" request, ").Append(Rt).Append("CallContext context) =>\n");
            b.Append("            throw new ").Append(Rt).Append("InvalidMethodError(\"invalid service method ").Append(m.Name).Append("\");\n");
        }
        b.Append("    }\n");
    }

    private static void Proxy(StringBuilder b, ServiceDescriptor s, MethodNames names)
    {
        b.Append("    /// <summary>\n");
        b.Append("    /// Calls <c>").Append(s.FullName).Append("</c>. Construct it with an instance name to address a\n");
        b.Append("    /// service registered under one; <see cref=\"").Append(Rt).Append("ServiceProxy.Init\"/> before calling.\n    /// </summary>\n");
        b.Append("    public partial class Proxy : ").Append(Rt).Append("ServiceProxy\n    {\n");
        b.Append("        public Proxy(").Append(Rt).Append("Context context, string serviceName = ServiceFullName) : base(context, serviceName) =>\n");
        b.Append("            context.Factory.Register(Descriptor);\n");
        foreach (var m in s.Methods)
        {
            if (m.IsClientStreaming) continue;
            var req = Names.MessageClass(m.InputType);
            var res = Names.MessageClass(m.OutputType);
            b.Append("\n        /// <summary><c>").Append(Signature(m)).Append("</c></summary>\n");
            if (m.IsServerStreaming)
            {
                b.Append("        public ").Append(Async).Append('<').Append(res).Append("> ").Append(names.Plain[m.Name]).Append('(')
                    .Append(req).Append(" request, ").Append(Rt).Append("StreamOptions? options = null,\n");
                b.Append("            ").Append(Token).Append(" cancellationToken = default) =>\n");
                b.Append("            CallStream(\"").Append(m.Name).Append("\", request, ").Append(res).Append(".Parser, options, cancellationToken);\n");
            }
            else
            {
                b.Append("        public ").Append(Tasks).Append("Task<").Append(res).Append("> ").Append(names.Async[m.Name]).Append('(')
                    .Append(req).Append(" request, ").Append(Rt).Append("CallOptions? options = null,\n");
                b.Append("            ").Append(Token).Append(" cancellationToken = default) =>\n");
                b.Append("            CallAsync(\"").Append(m.Name).Append("\", request, ").Append(res).Append(".Parser, options, cancellationToken);\n");
            }
        }
        b.Append("    }\n");
    }
}
